### ISSUE TITLE
Two options for background: preset gradient or solid hex color

### ISSUE THREAD

**Issue by nullmaxwell** [nullmaxwell/HomeHub#5]
User should have the option to choose from either the preset gradient background in the options menu or a single solid hexadecimal color such as #5292c1

When clicking the settings cog, I'm thinking the options could look something like this:
![image](https://github.com/nullmaxwell/HomeHub/assets/19422829/cd800cb3-cf87-4292-8db0-e52f0f3f8780)

Note: last options on the mock up component (gradient theme and color code) should only be visible when one of the corresponding radio(?) buttons are selected

**Comment by okni-c** [comment]
![image](https://github.com/nullmaxwell/HomeHub/assets/77583463/575e8a70-467b-4d54-a1bf-e49a0a153026)

Added this feature.
